### ISSUE TITLE
meta_test_head is None on demo

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmfewshot#14]
The error occurs when running `demo_metric_classifier_1shot_inference` with a custom trained `NegMargin` model. The `meta_test_head` is None. Testing the model with `dist_test` works as expected though. I am not sure why it didn't save the meta test head. A comment [here](https://github.com/open-mmlab/mmfewshot/blob/217aff67f7b57cc5961633e3521318e3dd671174/mmfewshot/classification/models/classifiers/base_finetune.py#L19) says that it is only built and run on testing. I am not sure what that means though.

The model config is the same as the standard in other config files:

```
model = dict(
    type='NegMargin',
    backbone=dict(type='Conv4'),
    head=dict(
        type='NegMarginHead',
        num_classes=6,
        in_channels=1600,
        metric_type='cosine',
        margin=-0.01,
        temperature=10.0),
    meta_test_head=dict(
        type='NegMarginHead',
        num_classes=6,
        in_channels=1600,
        metric_type='cosine',
        margin=0.0,
        temperature=5.0))
```

Otherwise, the config file itself is similar to other `neg_margin` config files for the `cube` dataset.

**Comment by linyq17** [comment]
The meta testing of `NegMargin` will build and finetune a new head for each task. Currently, the demo does not support methods that require fine-tuning during testing since the inference codes do not introduce any code of training.

**Comment by rlleshi** [comment]
What if we process support images for the same task as was during training and validation? In this case, a new head won't be needed because it has already been fine-tuned during the meta testing of the training phase. In other words, the head formed during training could be directly utilized and the step of fine-tuning a new head skipped. Does this make sense?

Alternatively, do you have any other suggestions to do inference while serving these models (which are performing better for my task) in production?

**Comment by linyq17** [comment]
If you only need to test a few tasks, it might work by saving all the pre-trained weights. As for the inference, I think it is possible to compute the weights of fc layer from extracted features mutually since it only trains a linear head.
