### ISSUE TITLE
IterBasedRunner chosen instead of EpochBasedRunner

### ISSUE THREAD

**Issue by Chan-Sun** [open-mmlab/mmfewshot#15]
Hi！ First of all, very appreciate of your excellent job and it really helps me a lot for my own research.

In the past few weeks, I was trying to re-implement some fsod work based on mmdet. Since MMFewShot was released, I spent a few days reading the source code,  and noticed a little difference. In mmdet-style config file,, EpochBasedRunner is default runner type, but IterBasedRunner was chosen in this project.

I wonder if there is any help or rise on results through this change. If it really helps, do you have any suggestion on converting runner from EpochBasedRunner to IterBasedRunner, for example some empirical formula to calculate max_iter and evaluation interval between EpochBasedRunner and IterBasedRunner, since i would like to conduct fsod models on some domain-specific dataset.

**Comment by linyq17** [comment]
There are some reasons for using `IterBasedRunner` as default:

- In most of fsod papers or released codebases, their training schedules use the number of iteration as default. To reproduce their results, we follow this convention.

- In few shot fine-tuning settings, the number of available images is usually small, and sometimes it can be less than five in one epoch. Using `IterBasedRunner` with `InfiniteSampler` can avoid frequently initializing dataloader workers between epoch for faster training speed.

Converting runners from `EpochBasedRunner` to `IterBasedRunner` only needs to know the length of the dataset. The number of iteration is equal to the `num_epoch` * (`dataset_len` // `batch_size`), where `batch_size` = `num_gpus` * `samples_per_gpu`. The converted evaluation interval also can be calculated in this way.

**Comment by Chan-Sun** [comment]
> 

very clear answer, many thanks again for your excellent work
