### ISSUE TITLE
Model deployment

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmfewshot#24]
Hi, do you plan to support model deployment like in [mmcls](https://github.com/open-mmlab/mmclassification/tree/master/tools/deployment) any time soon?

**Comment by linyq17** [comment]
Hi, currently the model deployment is not in the plan.

**Comment by rlleshi** [comment]
any general guidelines/tips that you could give?

**Comment by linyq17** [comment]
You may be interested in the [mmcls](https://mmclassification.readthedocs.io/en/latest/tools/pytorch2onnx.html) docs  or [mmdet](https://mmdetection.readthedocs.io/en/latest/tutorials/pytorch2onnx.html) docs about model deployment.
