### ISSUE TITLE
FileNotFoundError: FewShotCocoDefaultDataset: [Errno 2] No such file or directory: 'data/few_shot_ann/coco/benchmark_10shot/full_box_10shot_OD_trainval.json'

### ISSUE THREAD

**Issue by Williamlizl** [open-mmlab/mmfewshot#31]
I use my own coco-fromat datasets,  and then it shows the error. I need to spilt the all datasets? And is there some tools to split?

**Comment by linyq17** [comment]
Hi, more details about custom datasets can refer to  `https://mmfewshot.readthedocs.io/en/latest/detection/customize_dataset.html`. The default datasets are designed for few shot VOC and Coco settings. The dataset split can be configured by `ann_shot_filter`.

**Comment by Williamlizl** [comment]
> Hi, more details about custom datasets can refer to `https://mmfewshot.readthedocs.io/en/latest/detection/customize_dataset.html`. The default datasets are designed for few shot VOC and Coco settings. The dataset split can be configured by `ann_shot_filter`.

`mmfewshot
├── mmfewshot
├── tools
├── configs
├── data
│   ├── coco
│   │   ├── annotations
│   │   ├── train2014
│   │   ├── val2014
│   │   ├── train2017 (optional)
│   │   ├── val2017 (optional)
│   ├── few_shot_ann
│   │   ├── coco
│   │   │   ├── annotations
│   │   │   │   ├── train.json
│   │   │   │   ├── val.json
│   │   │   ├── attention_rpn_10shot (for coco17)
│   │   │   ├── benchmark_10shot
│   │   │   ├── benchmark_30shot`

So how to produce the 10shot folder?The structure of datasets is like this, but in the step 3, there is no split datasets
├── data
     │   ├── annotations
     │   ├── train2014
     │   ├── val2014

**Comment by Williamlizl** [comment]
> Hi, more details about custom datasets can refer to `https://mmfewshot.readthedocs.io/en/latest/detection/customize_dataset.html`. The default datasets are designed for few shot VOC and Coco settings. The dataset split can be configured by `ann_shot_filter`.

/mmfewshot-main/mmfewshot/detection/datasets/coco.py

benchmark_10shot file is needed? So how to produce such shot file
`coco_benchmark = {
        f'{shot}SHOT': [
            dict(
                type='ann_file',
                ann_file=f'data/few_shot_ann/coco/benchmark_{shot}shot/'
                f'full_box_{shot}shot_{class_name}_trainval.json')`

**Comment by linyq17** [comment]
These files are prepared for common settings. The preparation details can be found in `https://github.com/open-mmlab/mmfewshot/blob/main/tools/data/detection/coco/README.md`

**Comment by Williamlizl** [comment]
> These files are prepared for common settings. The preparation details can be found in `https://github.com/open-mmlab/mmfewshot/blob/main/tools/data/detection/coco/README.md`

Yes, but how to  produce such 10shot foramt file on my own coco-format datasets?

**Comment by linyq17** [comment]
The dataset split can be generated online by configuring `ann_shot_filter`. If you still want to generate the 10 shots mutually you can refer to `https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_coco_few_shot.py`.

**Comment by Williamlizl** [comment]
> The dataset split can be generated online by configuring `ann_shot_filter`. If you still want to generate the 10 shots mutually you can refer to `https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_coco_few_shot.py`.

Ok, I will try it,

**Comment by Williamlizl** [comment]
> The dataset split can be generated online by configuring `ann_shot_filter`. If you still want to generate the 10 shots mutually you can refer to `https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_coco_few_shot.py`.

You mean the 10 shot will be produced automatically when I train the model in step 3?
`CUDA_VISIBLE_DEVICES=2,3 ./tools/detection/dist_train.sh ./configs/detection/fsce/coco/fsce_r101_fpn_coco_10shot-fine-tuning.py 2`
`FewShotCocoDefaultDataset: [Errno 2] No such file or directory: 'data/few_shot_ann/coco/benchmark_10shot/full_box_10shot_OD_trainval.json'FileNotFoundError
: FewShotCocoDefaultDataset: [Errno 2] No such file or directory: 'data/few_shot_ann/coco/benchmark_10shot/full_box_10shot_OD_trainval.json'`

in the ./mmfewshot-main/configs/detection/fsce/coco/fsce_r101_fpn_coco_10shot-fine-tuning.py
`data = dict(
    train=dict(
        type='FewShotCocoDefaultDataset',
        ann_cfg=[dict(method='FSCE', setting='10SHOT')],
        num_novel_shots=10,
        num_base_shots=10))`

so i need to change the 10shot file saved path?
