### ISSUE TITLE
Is there a plan to support Windows platform ?

### ISSUE THREAD

**Issue by Atumyugi** [open-mmlab/mmfewshot#32]
I see Linux (Windows is not officially supported)
Is there a plan to support Windows platform? Thanks.

**Comment by Atumyugi** [comment]
In other words, will there be any unexpected errors when I install this project on the Windows platform? I want to port the current code to the Windwos platform.

**Comment by linyq17** [comment]
As this codebase is heavily based on mmcv, mmdet and mmcls, the support of windows mainly depends on these upstream libraries.

**Comment by Atumyugi** [comment]
Thanks :)

**Comment by rlleshi** [comment]
Should probably work with WSL I guess

**Comment by fcakyon** [comment]
> As this codebase is heavily based on mmcv, mmdet and mmcls, the support of windows mainly depends on these upstream libraries.

mmcv mmcls and mmdet offically support windows, so mmfewshot is also supported on windows?

**Comment by BIGWangYuDong** [comment]
MMFewShot is support Windows now.
