### ISSUE TITLE
ImportError: cannot import name 'DistributedSampler' from 'mmcls.datasets.builder'

### ISSUE THREAD

**Issue by wwwbq** [open-mmlab/mmfewshot#39]
使用tools/detection/test.py对TFA模型评估时发生如上报错，检查源码发现在mmfewshot/__init__.py中有from .classification import *一行，在后续调用mmcls的mmcls.datasets.builder文件中没有实现DistributedSampler。只有把from .classification import * 注释掉才能正常对detection模型进行测试

**Comment by linyq17** [comment]
Thanks for reporting. It has been fixed in   #38.

**Comment by xiaofeng-c** [comment]
yeah,and when eval for classification,i just modify the "from mmcls.datasets.builder import DATASETS, DistributedSampler, worker_init_fn" to "from mmcls.datasets.builder import DATASETS, worker_init_fn",it just a little slow.
