### ISSUE TITLE
Few-shot instead of one-shot in demo inference

### ISSUE THREAD

**Issue by rlleshi** [open-mmlab/mmfewshot#41]
Currently, the demo script (classification) takes only one sample in the support set. It uses the `process_support_images()` method to forward the support set. How to modify this in order to allow for more than one sample in the support set?

One idea could be to place another set of support images in a different folder and then forward that as well. Then the `model.before_forward_support()` method can be modified if it resets the features. For e.g. for `meta_baseline_head`, it is resetting saved features.

Then (again for meta_baseline), `meta_baseline_head.before_forward_query` would also have to be modified since it is replacing the `self.mean_support_feats` with the mean of the new support set.

Would these two changes in this case be enough to adapt for a few-shot instead of a one-shot inference?

**Comment by linyq17** [comment]
To adapt few-shot inference, forwarding support images and labels is enough. The `model.before_forward_support()` will handle them according to their labels. Also, the labels should in the range(0, number of classes).

**Comment by rlleshi** [comment]
Hi @linyq17 

It's actually not working like that. I am forwarding a couple of support images and labels using `process_support_images()` but only the last forwarded images are being used to build the support features and labels.

In other words, if forwarding two different sets of support images, `set-1`, and `set-2` (in this order), the results of the inference will be the selfsame as if forwarding only the latter `set-2`.

As already mentioned above, this seems to me to be the case because in [before_forward_support()](https://github.com/open-mmlab/mmfewshot/blob/1ad6ff7dca356198a525ba5f963078fc037bb046/mmfewshot/classification/models/heads/meta_baseline_head.py#L93) for `meta_baseline_head` we are resetting the support features.

**Comment by linyq17** [comment]
It seems the `process_support_images` was called multiple times. Each time this function will reset the head and the code is in [here](https://github.com/open-mmlab/mmfewshot/blob/main/mmfewshot/classification/apis/inference.py#L71). If the support images need to be passed multiple times, this line of code needs to be modified.

**Comment by rlleshi** [comment]
Exactly. I had modified only that and I got different results. But wanted to confirm once. Thanks.

`before_forward_query()` (for meta baseline) on the other hand need not be modified.
