### ISSUE TITLE
FewShotCocoDefaultDataset中coco_benchmark的ann_file路径无法自定义

### ISSUE THREAD

**Issue by wwwbq** [open-mmlab/mmfewshot#60]
在mmfewshot/detection/datasets/coco.py/FewShotCocoDefaultDataset 中的coco_benchmark固定了数据集路径为f'data/few_shot_ann/coco/benchmark_{shot}shot/full_box_{shot}shot_{class_name}_trainval.json'。但是我的few_shot_ann路径和上面不同，并且FewShotCocoDefaultDataset没有办法接受数据集路径的参数，希望可以增加此参数

**Comment by linyq17** [comment]
Thanks for the feedback. Currently, they only can be modified in `FewShotCocoDefaultDataset` mutually.

**Comment by Maojianzeng** [comment]
> 在mmfewshot/detection/datasets/coco.py/FewShotCocoDefaultDataset 中的coco_benchmark固定了数据集路径为f'data/few_shot_ann/coco/benchmark_{shot}shot/full_box_{shot}shot_{class_name}_trainval.json'。但是我的few_shot_ann路径和上面不同，并且FewShotCocoDefaultDataset没有办法接受数据集路径的参数，希望可以增加此参数

[https://github.com/open-mmlab/mmfewshot/blob/main/configs/detection/_base_/datasets/fine_tune_based/base_coco.py](url)在这里修改data_root和ann_file呢
