### ISSUE TITLE
How to prepare my own datasete like coco and voc format to do fewshot training?

### ISSUE THREAD

**Issue by lnq325805524** [open-mmlab/mmfewshot#70]
Looking forward to your reply. Thanks!

**Comment by iazt** [comment]
@lnq325805524 were you able to train with your own dataset? Could you share if it worked for you?

**Comment by lnq325805524** [comment]
您的邮件已收到，谢谢

**Comment by lnq325805524** [comment]
@iazt Yeah. I first made my own dataset using the code from  [https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_voc_few_shot.py](url).  Then please look at [https://mmfewshot.readthedocs.io/en/latest/](url) about training your own dataset.
