### ISSUE TITLE
For VOC dataset, How to get AP and AP75？

### ISSUE THREAD

**Issue by kike-0304** [open-mmlab/mmfewshot#77]
For VOC dataset, How to get AP and AP75？

**Comment by BIGWangYuDong** [comment]
VOC dataset is defaulted to use AP50 as default. If you want to use AP75 or AP0.5:0.95:0.05, you can change the default of iou_thr to 0.75 or [0.5+0.05i for i in range(9)]
https://github.com/open-mmlab/mmfewshot/blob/3f3b6b4fd0b4f7ac7426705a2f6354b47d1bfa8a/mmfewshot/detection/datasets/voc.py#L417-L424
