### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by isJunCheng** [open-mmlab/mmfewshot#82]
According to the document, the following errors occur during training. I don't know how to solve them. Has anyone encountered them.
TypeError: __init__() got an unexpected keyword argument 'persistent_workers'

**Comment by isJunCheng** [comment]
> Please use English or English & Chinese for issues so that we could have broader discussion.

ok

**Comment by isJunCheng** [comment]
I looked at the official documents provided by pytorch. The parameter 'persistent_workers' can only be used when torch==1.7.0+.

**Comment by isJunCheng** [comment]
I have a new problem now
![image](https://user-images.githubusercontent.com/44466856/167806329-f9c91f4f-d652-46ec-b289-ff57358957f7.png)
As shown in the figure above, the training is aborted during initialization.

**Comment by guanlaoshi** [comment]
> According to the document, the following errors occur during training. I don't know how to solve them. Has anyone encountered them. TypeError: **init**() got an unexpected keyword argument 'persistent_workers'

可能不是pytorch 的问题，如果使用的是TwoBranchDataloader模式的话也会出现这种问题：
可以在mmfewshot/detection/datasets/builder.py 第311行左右添加如下代码：
```python
        # wrap two dataloaders with dataloader wrapper
        #----------20230321添加以下
        #由于会出现TypeError: __init__() got an unexpected keyword argument 'persistent_workers'
        #所以在这删掉persistent_workers关键对
        del kwargs['persistent_workers']
        # ----------20230321添加以上
        data_loader = TwoBranchDataloader(
            main_data_loader=main_data_loader,
            auxiliary_data_loader=auxiliary_data_loader,
            **kwargs)
```
