### ISSUE TITLE
Don't find the “frozen_parameters” parameter in the relevant source code

### ISSUE THREAD

**Issue by wwwbq** [open-mmlab/mmfewshot#83]
I found that the “frozen_parameters” parameter is used in many detection models, but I have not found where this parameter is used in the relevant source code. Which part of the source code should I see?

**Comment by BIGWangYuDong** [comment]
https://github.com/open-mmlab/mmfewshot/blob/2cda666e5c50586a73516f860b66729593af0d4a/mmfewshot/detection/models/builder.py#L16-L24

**Comment by wwwbq** [comment]
Thanks for your help !

**Comment by wwwbq** [comment]
> The code is as follow
> 
> https://github.com/open-mmlab/mmfewshot/blob/2cda666e5c50586a73516f860b66729593af0d4a/mmfewshot/detection/models/builder.py#L16-L24

Thanks for your help !
