### ISSUE TITLE
confused about `samples_per_gpu` of meta_dataloader

### ISSUE THREAD

**Issue by Wei-i** [open-mmlab/mmfewshot#9]
https://github.com/open-mmlab/mmfewshot/blob/486c8c2fd7929880eab0dfcd73a3dd3a512ddfbe/configs/detection/_base_/datasets/nway_kshot/base_voc.py#L106

Hi, thanks for your great work in fsod. 
I want to know why the value of samples_per_gpu is not 15 instead of 16 for voc base training.
Hope you can help me.

**Comment by linyq17** [comment]
The `model_init` dataset is used for initializing the meta-based models before testing. Assuming we test the model with VOC 2 shot setting, we will have 2x15 instances, which means the length of support dataset is 30. The `samples_per_gpu` indicates the batch size in forwarding the support dataset. Also, please note that in multi-gpu setting each GPU will forward the whole support dataset to get the same initialized model.

**Comment by Wei-i** [comment]
sorry, I still don't know why samples_per_gpu  is not 15.

**Comment by Wei-i** [comment]
In `mmfewshot/mmfewshot/detection/models/detectors/meta_rcnn.py`,  when I execute this function:
```
        assert len(gt_labels) == img.size(0), 'Support instance have more than two labels'
        feats = self.extract_support_feat(img) # [16, 1024, 14, 14]
        roi_feat = self.roi_head.extract_support_feats(feats)  # [16, 2048]       
```
I get `gt_label`:
![image](https://user-images.githubusercontent.com/47490392/143217886-471b84c8-5a99-4b11-8e6b-08c6da7bd304.png)

However, there are two labels about `[0,1]`.
So what is the meaning of `assert len(gt_labels) == img.size(0), 'Support instance have more than two labels'` ?

**Comment by linyq17** [comment]
The support image will generate an instance mask, so each image only can contain one bbox. And the order of loading the support dataset during the model initialization stage doesn't matter. After traversaling the whole support dataset, the model will get the average features for each class. The `samples_per_gpu` is the batch size of traversaling the whole support dataset.

**Comment by Wei-i** [comment]
Thanks :)  I found I have a mistake,  `samples_per_gpu` of support set  is used for val step instead of train step, which is provide by another with `query_data`.

**Comment by Wei-i** [comment]
```
            # the official code use the first class background score as final
            # background score, while this code use average of all classes'
            # background scores instead.
```
I want to know that if a image contains more than 1 class-instance,  the official code and your code only select  a (random) class and ignore others.   It is right?

**Comment by linyq17** [comment]
yes, it only selects one instance for each image.

**Comment by Wei-i** [comment]
Thanks :)
