### ISSUE TITLE
coco dataset？

### ISSUE THREAD

**Issue by kike-0304** [open-mmlab/mmfewshot#92]
我的coco数据目录是这样的：
data
--coco
  ----annotations
  ----train2014
  ----val2014
--few_shot_ann
  ----coco
    ------benchmark_10shot
     -------- ...
当我运行fsce下的coco预训练config时，会报错：no such file or directory: 'data/few_shot_ann/coco/annotaions/train.json'
请问这个train.json是哪里来的，预训练的标签不是应该调用coco文件夹下的annotations吗？
另外我在data preparation找到一个trainvalno5k.json和5k.json，请问是这两个json文件吗？
期待您的回答！

**Comment by jx6688110** [comment]
Actually，if you use pycharm to run train.py,i think data should be in a same directory with train.py.

**Comment by kike-0304** [comment]
> Actually，if you use pycharm to run train.py,i think data should be in a same directory with train.py.
我把coco2014里面的annotations下的两个json文件改名为train.json和val.json就可以跑了，但是我不确定这样改对不对

**Comment by jx6688110** [comment]
![QQ图片20220525150702](https://user-images.githubusercontent.com/59209158/170201752-c7f581c8-ab46-491e-a235-b61bbfbf7e09.png)

This is my directory .

**Comment by kike-0304** [comment]
> ![QQ图片20220525150702](https://user-images.githubusercontent.com/59209158/170201752-c7f581c8-ab46-491e-a235-b61bbfbf7e09.png)
> 
> This is my directory .

请问这一部分两个json文件是怎么得到的？
![image](https://user-images.githubusercontent.com/73974837/170203329-ae64a558-3a96-4d0b-a8f8-3e85fcd0068d.png)

**Comment by jx6688110** [comment]
[[https://github.com/open-mmlab/mmfewshot/blob/main/tools/data/detection/coco/README.md](url)](https://github.com/open-mmlab/mmfewshot/blob/main/tools/data/detection
![QQ图片20220525152237](https://user-images.githubusercontent.com/59209158/170204812-fc29aa75-2043-48c8-b0cb-88618ea704e4.png)

**Comment by kike-0304** [comment]
> [[https://github.com/open-mmlab/mmfewshot/blob/main/tools/data/detection/coco/README.md](url)](https://github.com/open-mmlab/mmfewshot/blob/main/tools/data/detection ![QQ图片20220525152237](https://user-images.githubusercontent.com/59209158/170204812-fc29aa75-2043-48c8-b0cb-88618ea704e4.png)

感谢！
